# Generated by Django 3.1 on 2020-08-31 16:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockReading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_update_date', models.DateTimeField(auto_now=True)),
                ('reference_id', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(code='invalid_reference_id', message='The reference_id field has to be 13 digits.', regex='^\\d{13}$')])),
                ('expiry_date', models.DateField()),
            ],
        ),
    ]
