# Generated by Django 3.1 on 2020-08-31 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_auto_20200831_1337'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='stockreading',
            name='unique_reference_id_last',
        ),
        migrations.RemoveField(
            model_name='stockreading',
            name='last',
        ),
    ]
